/**
 * Descarga de informes IA Fadey: Excel (.xlsx con gráficos como imagen) y PDF (página imprimible con gráficos).
 */
import { chartToSvg, formatReportValue, svgToPngBase64 } from './fadeyReportCharts';

const LABELS = {
  es: {
    vsPrev: 'vs período anterior',
    keyPoints: 'Lo más importante',
    records: 'registro(s)',
    print: 'Imprimir / Guardar como PDF',
    generated: 'Generado por IA Fadey',
    summary: 'Resumen',
    charts: 'Gráficos',
    detail: 'Detalle',
    footer: 'Resto Fadey · Informe generado automáticamente',
    kpiHead: ['Indicador', 'Valor', 'Variación'],
    sheet: 'Hoja',
    locale: 'es-PE',
  },
  en: {
    vsPrev: 'vs previous period',
    keyPoints: 'Key takeaways',
    records: 'record(s)',
    print: 'Print / Save as PDF',
    generated: 'Generated by Fadey AI',
    summary: 'Summary',
    charts: 'Charts',
    detail: 'Detail',
    footer: 'Resto Fadey · Automatically generated report',
    kpiHead: ['Indicator', 'Value', 'Change'],
    sheet: 'Sheet',
    locale: 'en-US',
  },
};

function labelsFor(report) {
  return LABELS[report?.lang === 'en' ? 'en' : 'es'];
}

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function fileBaseName(report) {
  const slug = String(report.title || 'informe')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return `${slug}-${report.from || ''}${report.to && report.to !== report.from ? `_${report.to}` : ''}`;
}

function generatedLabel(report) {
  try {
    return new Date(report.generated_at || Date.now()).toLocaleString(labelsFor(report).locale, { timeZone: 'America/Lima' });
  } catch {
    return '';
  }
}

function kpiDelta(k, L) {
  if (k.delta == null) return '';
  return `${k.delta >= 0 ? '▲ +' : '▼ '}${Number(k.delta).toFixed(1)}% ${L.vsPrev}`;
}

/* ─────────────────────────── PDF ─────────────────────────── */

function buildPdfHtml(report) {
  const L = labelsFor(report);
  const kpis = report.kpis.map((k) => `
    <div class="kpi">
      <div class="kpi-label">${esc(k.label)}</div>
      <div class="kpi-value">${esc(formatReportValue(k.value, k.format))}</div>
      ${k.delta != null ? `<div class="kpi-delta ${k.delta >= 0 ? 'up' : 'down'}">${esc(kpiDelta(k, L))}</div>` : ''}
    </div>`).join('');
  const insights = report.insights.length
    ? `<h2>${L.keyPoints}</h2><ul class="insights">${report.insights.map((t) => `<li>${esc(t)}</li>`).join('')}</ul>`
    : '';
  const charts = report.charts.map((c) => `<div class="chart">${chartToSvg(c)}</div>`).join('');
  const tables = report.tables.map((t) => {
    const head = t.columns.map((c) => `<th class="${c.format ? 'num' : ''}">${esc(c.label)}</th>`).join('');
    const body = t.rows.map((r) => `<tr>${t.columns.map((c) => `<td class="${c.format ? 'num' : ''}">${esc(c.format ? formatReportValue(r[c.key], c.format) : r[c.key])}</td>`).join('')}</tr>`).join('');
    const totals = t.totals
      ? `<tr class="totals">${t.columns.map((c) => {
        const v = t.totals[c.key];
        return `<td class="${c.format ? 'num' : ''}">${v == null ? '' : esc(c.format ? formatReportValue(v, c.format) : v)}</td>`;
      }).join('')}</tr>`
      : '';
    return `<div class="table-block"><h3>${esc(t.title)} <span>(${t.rows.length} ${L.records})</span></h3>
      <table><thead><tr>${head}</tr></thead><tbody>${body}${totals}</tbody></table></div>`;
  }).join('');

  return `<!doctype html><html lang="${report.lang === 'en' ? 'en' : 'es'}"><head><meta charset="utf-8"><title>${esc(fileBaseName(report))}</title>
<style>
  @page { size: A4; margin: 14mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #0f172a; margin: 0; padding: 24px; background: #f1f5f9; }
  .page { max-width: 820px; margin: 0 auto; background: #fff; padding: 28px; border-radius: 12px; }
  .toolbar { max-width: 820px; margin: 0 auto 12px; display: flex; justify-content: flex-end; gap: 8px; }
  .toolbar button { background: #2563eb; color: #fff; border: 0; border-radius: 8px; padding: 10px 16px; font-size: 14px; font-weight: 600; cursor: pointer; }
  header { border-bottom: 3px solid #2563eb; padding-bottom: 12px; margin-bottom: 18px; }
  header .rest { font-size: 13px; color: #475569; text-transform: uppercase; letter-spacing: .05em; }
  header h1 { margin: 4px 0; font-size: 24px; }
  header .sub { font-size: 14px; color: #334155; }
  header .gen { font-size: 11px; color: #64748b; margin-top: 4px; }
  h2 { font-size: 16px; margin: 22px 0 10px; color: #1e3a8a; }
  h3 { font-size: 14px; margin: 18px 0 8px; }
  h3 span { font-weight: 400; color: #64748b; font-size: 12px; }
  .kpis { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }
  .kpi { border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px 12px; background: #f8fafc; }
  .kpi-label { font-size: 11px; color: #64748b; }
  .kpi-value { font-size: 18px; font-weight: 700; margin-top: 2px; }
  .kpi-delta { font-size: 10px; margin-top: 2px; }
  .kpi-delta.up { color: #059669; } .kpi-delta.down { color: #dc2626; }
  .insights { margin: 0; padding-left: 18px; font-size: 13px; line-height: 1.5; }
  .chart { border: 1px solid #e2e8f0; border-radius: 10px; margin: 12px 0; overflow: hidden; page-break-inside: avoid; }
  .chart svg { width: 100%; height: auto; display: block; }
  table { width: 100%; border-collapse: collapse; font-size: 11.5px; }
  th { background: #1e3a8a; color: #fff; text-align: left; padding: 6px 8px; }
  td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) td { background: #f8fafc; }
  tr.totals td { font-weight: 700; background: #e0e7ff !important; }
  .num { text-align: right; white-space: nowrap; }
  .table-block { page-break-inside: auto; }
  thead { display: table-header-group; }
  footer { margin-top: 24px; font-size: 10px; color: #94a3b8; text-align: center; }
  @media print {
    body { background: #fff; padding: 0; }
    .page { padding: 0; border-radius: 0; max-width: none; }
    .toolbar { display: none; }
  }
</style></head><body>
<div class="toolbar"><button onclick="window.print()">${L.print}</button></div>
<div class="page">
  <header>
    ${report.restaurant ? `<div class="rest">${esc(report.restaurant)}</div>` : ''}
    <h1>${esc(report.title)}</h1>
    <div class="sub">${esc(report.subtitle)}</div>
    <div class="gen">${L.generated} · ${esc(generatedLabel(report))}</div>
  </header>
  <h2>${L.summary}</h2>
  <div class="kpis">${kpis}</div>
  ${insights}
  ${charts ? `<h2>${L.charts}</h2>${charts}` : ''}
  ${tables ? `<h2>${L.detail}</h2>${tables}` : ''}
  <footer>${L.footer}</footer>
</div>
<script>window.addEventListener('load', function () { setTimeout(function () { window.print(); }, 400); });</script>
</body></html>`;
}

export function exportReportPdf(report) {
  const html = buildPdfHtml(report);
  const win = window.open('', '_blank');
  if (!win) {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${fileBaseName(report)}.html`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 5000);
    return;
  }
  win.document.open();
  win.document.write(html);
  win.document.close();
}

/* ─────────────────────────── Excel ─────────────────────────── */

const XL_FORMATS = {
  money: '"S/" #,##0.00',
  pct: '0.0%',
  int: '#,##0',
  number: '#,##0.00',
};

function xlValue(v, format) {
  if (v == null || v === '') return null;
  if (!format) return v;
  const n = Number(v);
  if (!Number.isFinite(n)) return v;
  return format === 'pct' ? n / 100 : n;
}

function safeSheetName(name, used, fallback = 'Hoja') {
  let base = String(name || fallback).replace(/[[\]:*?/\\]/g, ' ').trim().slice(0, 28) || fallback;
  let candidate = base;
  let i = 2;
  while (used.has(candidate.toLowerCase())) {
    candidate = `${base.slice(0, 25)} ${i}`;
    i += 1;
  }
  used.add(candidate.toLowerCase());
  return candidate;
}

const HEADER_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A8A' } };
const TOTAL_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E7FF' } };
const ZEBRA_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
const BORDER = { bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } } };

export async function exportReportExcel(report) {
  const { default: ExcelJS } = await import('exceljs');
  const wb = new ExcelJS.Workbook();
  const L = labelsFor(report);
  wb.creator = report.lang === 'en' ? 'Fadey AI' : 'IA Fadey';
  wb.created = new Date();
  const used = new Set();

  const ws = wb.addWorksheet(safeSheetName(L.summary, used, L.sheet), { views: [{ showGridLines: false }] });
  ws.columns = [{ width: 34 }, { width: 22 }, { width: 34 }, { width: 14 }, { width: 14 }, { width: 14 }];
  ws.mergeCells('A1:F1');
  ws.getCell('A1').value = report.title;
  ws.getCell('A1').font = { size: 18, bold: true, color: { argb: 'FF0F172A' } };
  ws.mergeCells('A2:F2');
  ws.getCell('A2').value = [report.restaurant, report.subtitle].filter(Boolean).join(' · ');
  ws.getCell('A2').font = { size: 12, color: { argb: 'FF334155' } };
  ws.mergeCells('A3:F3');
  ws.getCell('A3').value = `${L.generated} · ${generatedLabel(report)}`;
  ws.getCell('A3').font = { size: 9, italic: true, color: { argb: 'FF64748B' } };

  let row = 5;
  const kpiHead = ws.getRow(row);
  kpiHead.values = L.kpiHead;
  kpiHead.eachCell((c) => { c.fill = HEADER_FILL; c.font = { bold: true, color: { argb: 'FFFFFFFF' } }; });
  row += 1;
  report.kpis.forEach((k) => {
    const r = ws.getRow(row);
    r.getCell(1).value = k.label;
    r.getCell(2).value = xlValue(k.value, k.format);
    if (XL_FORMATS[k.format]) r.getCell(2).numFmt = XL_FORMATS[k.format];
    r.getCell(2).font = { bold: true };
    r.getCell(2).alignment = { horizontal: 'right' };
    if (k.delta != null) {
      r.getCell(3).value = kpiDelta(k, L);
      r.getCell(3).font = { color: { argb: k.delta >= 0 ? 'FF059669' : 'FFDC2626' } };
    }
    [1, 2, 3].forEach((i) => { r.getCell(i).border = BORDER; });
    row += 1;
  });

  if (report.insights.length) {
    row += 1;
    ws.getCell(`A${row}`).value = L.keyPoints;
    ws.getCell(`A${row}`).font = { bold: true, size: 13, color: { argb: 'FF1E3A8A' } };
    row += 1;
    report.insights.forEach((t) => {
      ws.mergeCells(`A${row}:F${row}`);
      const c = ws.getCell(`A${row}`);
      c.value = `• ${t}`;
      c.alignment = { wrapText: true, vertical: 'top' };
      ws.getRow(row).height = Math.max(18, Math.ceil(String(t).length / 110) * 16);
      row += 1;
    });
  }

  if (report.charts.length) {
    row += 1;
    ws.getCell(`A${row}`).value = L.charts;
    ws.getCell(`A${row}`).font = { bold: true, size: 13, color: { argb: 'FF1E3A8A' } };
    row += 1;
    for (const chart of report.charts) {
      try {
        const png = await svgToPngBase64(chartToSvg(chart));
        const imageId = wb.addImage({ base64: png.base64, extension: 'png' });
        const displayW = 700;
        const displayH = Math.round((png.height / png.width) * displayW);
        ws.addImage(imageId, { tl: { col: 0, row: row - 1 }, ext: { width: displayW, height: displayH } });
        row += Math.ceil(displayH / 20) + 1;
      } catch (_) {
        /* un gráfico que falle no bloquea el resto */
      }
    }
  }

  report.tables.forEach((t) => {
    const sheet = wb.addWorksheet(safeSheetName(t.title, used, L.sheet), { views: [{ state: 'frozen', ySplit: 3 }] });
    sheet.mergeCells(1, 1, 1, Math.max(t.columns.length, 2));
    sheet.getCell(1, 1).value = `${t.title} — ${report.subtitle}`;
    sheet.getCell(1, 1).font = { bold: true, size: 13 };
    const head = sheet.getRow(3);
    t.columns.forEach((c, i) => {
      const cell = head.getCell(i + 1);
      cell.value = c.label;
      cell.fill = HEADER_FILL;
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.alignment = { horizontal: c.format ? 'right' : 'left' };
    });
    t.rows.forEach((r, idx) => {
      const xr = sheet.getRow(4 + idx);
      t.columns.forEach((c, i) => {
        const cell = xr.getCell(i + 1);
        cell.value = xlValue(r[c.key], c.format);
        if (XL_FORMATS[c.format]) cell.numFmt = XL_FORMATS[c.format];
        cell.border = BORDER;
        if (idx % 2 === 1) cell.fill = ZEBRA_FILL;
      });
    });
    if (t.totals) {
      const tr = sheet.getRow(4 + t.rows.length);
      t.columns.forEach((c, i) => {
        const cell = tr.getCell(i + 1);
        const v = t.totals[c.key];
        cell.value = v == null ? null : xlValue(v, c.format);
        if (XL_FORMATS[c.format]) cell.numFmt = XL_FORMATS[c.format];
        cell.font = { bold: true };
        cell.fill = TOTAL_FILL;
      });
    }
    t.columns.forEach((c, i) => {
      const longest = Math.max(
        String(c.label).length,
        ...t.rows.slice(0, 200).map((r) => String(c.format ? formatReportValue(r[c.key], c.format) : (r[c.key] ?? '')).length),
      );
      sheet.getColumn(i + 1).width = Math.min(Math.max(longest + 3, 10), 48);
    });
    sheet.autoFilter = { from: { row: 3, column: 1 }, to: { row: 3 + t.rows.length, column: t.columns.length } };
  });

  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${fileBaseName(report)}.xlsx`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(a.href), 5000);
}
